### ISSUE TITLE
update crop_dataset.ipynb

### ISSUE THREAD

**Issue by JunMa11** [voreille/hecktor#11]
Hi @voreille ,

Thanks for organizing the great challenge.
It seems that the cropping and resampling notebook has not been updated.
https://github.com/voreille/hecktor/blob/master/notebooks/crop_dataset.ipynb

Looking forward to your update:)

**Comment by vandrearczyk** [comment]
Hi @JunMa11 , we updated the repository. You can now use src/resampling/resample.py
Vincent

**Comment by JunMa11** [comment]
Thank you:)
