### ISSUE TITLE
No module named 'src.resampling.utils'

### ISSUE THREAD

**Issue by JYeonLee** [voreille/hecktor#12]
When I try to run evaluate_predictions.ipynb in the notebook dir, I get the following message: 
```
No module named 'src.resampling.utils'
```
I cannot find the module in the src directory. Is there any solution?

**Comment by voreille** [comment]
Hi,
You can try running pip install -e . from the hecktor directory.
If you do that I advise using a virtual environment.
Best,
Valentin

**Comment by JYeonLee** [comment]
Thank you for your prompt reply.

I tried to run pip install -e . in the hecktor directory, however, it still does not run with the same error message.
I think there is not utils file in /src/resampling directory.

**Comment by voreille** [comment]
Hi,
My bad, I forgot that I removed this file. I have now updated the notebook and it should work.
Let me know if anything goes wrong.
Best,
Valentin

**Comment by JYeonLee** [comment]
Thank you!

It works well!
