### ISSUE TITLE
Adding out-of-the-box cropping code of testing code.

### ISSUE THREAD

**Issue by JunMa11** [voreille/hecktor#5]
There is no `gtvt` in testing sets.
Could you please updating the cropping code in the notebook?

**Comment by vandrearczyk** [comment]
I am not sure which notebook you are referring to. In any case, neither is made for the test set.
evaluate_predictions.ipynb is not meant to be used by the participants with the test set since we won't provide the ground truth.
crop_dataset.ipynb is not needed by the participants.

**Comment by JunMa11** [comment]
Dear @vandrearczyk 

Sorry, I thought [crop_dataset.ipynb](https://github.com/voreille/hecktor/blob/master/notebooks/crop_dataset.ipynb) is for training and testing data cropping.

Where is the code that I can use to crop the testing data?

Best,
Jun

**Comment by vandrearczyk** [comment]
No worries, you can check the Resample Data section in the README. 
Best,
Vincent

**Comment by JunMa11** [comment]
Thanks for your help very much.
I make it :)
