### ISSUE TITLE
wrong when using "evaluate_predictions.ipynb" to evaluate 3d dice

### ISSUE THREAD

**Issue by zs963048949** [voreille/hecktor#6]
I found the evaluated result wrong when I used the code "evaluate_predictions.ipynb".After,I made  a test. I used resampled gtvt data generated by the operation “python src/resampling/cli_resampling.py” as "prediction_folder" to evaluate 3d dice score,and I got the dice of 0.9528 instead of 1.Why?

**Comment by voreille** [comment]
Hi,

Thank you for noticing this. The problem you are facing certainly results from the nearest neighbor method used to resample. This method does not ensure image equality after two successive resampling operations, even for an intermediate domain with a finer resampling grid. The code provided on this Github is aimed to give you a starting point, but we encourage you to use other methods if you think they are more appropriate.

Best,

Valentin

**Comment by zs963048949** [comment]
Thank you.
